#封面,page_01.jpg
#产品配件,page_02.jpg
#安装说明,page_03.jpg
#快速入门指南,page_04.jpg
#按键介绍,page_05.jpg
#状态栏UI说明,page_06.jpg
#声呐信息区域-1,page_07.jpg
#声呐信息区域-2,page_08.jpg
#菜单说明,page_09.jpg
#声呐设置菜单,page_10.jpg
#声呐设置参数建议,page_11.jpg
#声呐保存,page_12.jpg
#声呐回放,page_13.jpg
#系统设置菜单,page_14.jpg
     