#Cover,page_01.jpg
#Product Accessories,page_02.jpg
#Installation Instructions,page_03.jpg
#Quick Start Guide,page_04.jpg
#Button Functions,page_05.jpg
#Top status bar,page_06.jpg
#Sonar Information Area--1,page_07.jpg
#Sonar Information Area--2,page_08.jpg
#Main Menu,page_09.jpg
#Sonar Parameter Settings,page_10.jpg
#Save Echoes,page_11.jpg
#History Playback,page_12.jpg
#System Settings,page_13.jpg
